browsername=chrome
url=https://www.amazon.in/
#path=\\src\\test\\resources\\TestData\\AmazonTestData.xlsx

#path=/src/test/resources/TestData/AmazonTestData.xlsx

#path=//src//test//resources//TestData//AmazonTestData.xlsx